name: "Move a card"
description: "Move a card from source column to destination column"
author: "deveshvasnani@gmail.com"

inputs:
  CARD_ID:
    description: "Card Id"
    required: true
  POSITION:
    description: "It can be ['top', 'bottom']"
    required: true
    default: "top"
  TO_COLUMN_ID:
    description: "To column"
    required: false
  REPOSITORY_TOKEN:
    description: "Token to perform action"
    required: true

outputs:
  response:
    description: "rest.js response"

runs:
  using: "node12"
  main: "index.js"